### PR TITLE
feat: add Svelte 4 support

### LINKED ISSUE #31: Svelte 4 Support
Support for [Svelte 4](https://svelte.dev/docs/v4-migration-guide) would be nice, specifically the bit about [SvelteComponentTyped](https://svelte.dev/docs/v4-migration-guide#sveltecomponenttyped-is-deprecated).

### PR DESCRIPTION
**Pull request by MattheousDT**
* Closes #31
* Replaces usage of `SvelteComponentTyped` with `SvelteComponent`
* Changes are backwards compatible so peer dependencies have been updated to allow between `^3.47.0` and `4.x.x`

### CODE REVIEW

**Review by stipsan — APPROVED** [review]
Thank you so much! 🎉

**Comment by stipsan** [comment]
@SocketSecurity ignore svelte-preprocess@5.0.4
@SocketSecurity ignore @sveltejs/kit@1.20.4
@SocketSecurity ignore undici@5.22.1

**Comment by stipsan** [comment]
Vercel is getting this build error:
```


Running "vercel build"
--
01:55:56.804 | Vercel CLI 30.2.3
01:55:57.363 | Installing dependencies...
01:56:02.963 |  
01:56:02.963 | > @portabletext/svelte@2.0.0 prepublish
01:56:02.963 | > npm run package && cd package
01:56:02.963 |  
01:56:03.338 |  
01:56:03.338 | > @portabletext/svelte@2.0.0 package
01:56:03.338 | > svelte-kit package
01:56:03.338 |  
01:56:03.407 |  
01:56:03.407 | ERROR
01:56:03.407 | Invalid command: package
01:56:03.407 |  
01:56:03.407 | Run `$ svelte-kit --help` for more info.
01:56:03.408 |  
01:56:03.419 | npm ERR! code 1
01:56:03.420 | npm ERR! path /vercel/path0
01:56:03.421 | npm ERR! command failed
01:56:03.421 | npm ERR! command sh -c npm run package && cd package

```

**Comment by MattheousDT** [comment]
I forgot that version bumping kit also meant it needed to use the new separate package module and the new routing so I've updated those too

**Comment by stipsan** [comment]
Getting this error on the Vercel deploy now:
```
 ERROR
    Invalid command: build

  Run `$ svelte-kit --help` for more info.
```

Looks like we have to move to using Vite? https://www.netlify.com/blog/migrating-breaking-changes-in-sveltekit/#:~:text=Loading%20Data%20Docs-,All%20in%20on%20Vite,-SvelteKit%20has%20gone

**Pull request merged**
